### ISSUE TITLE
用sublime package install 找不到插件

### ISSUE THREAD

**Issue by zefan1984** [toaol/sublime-translate#1]
用sublime **package install** 找不到插件

**Comment by toaol** [comment]
包名叫做 `ChineseTranslator`，只能在 Sublime Text 3 中使用。
刚刚看了一下，还能找到。
![image](https://cloud.githubusercontent.com/assets/10507812/15625503/40d63116-24db-11e6-93e8-4752e3857682.png)

**Comment by zefan1984** [comment]
谢谢，我早上安装的时候没有，后来直接git拉一下。


发自 网易邮箱大师
在2016年05月28日 13:52，娄涛 写道:

包名叫做 ChineseTranslator，只能在 Sublime Text 3 中使用。
刚刚看了一下，还能找到。

**Comment by 20Tauri** [comment]
If you look for a plugin that support Translation and SublimeText2, you can try DoxyDoxygen.

   - http://20tauri.free.fr/DoxyDoxygen/page_usage.html#translate
   - http://20tauri.free.fr/DoxyDoxygen/page_appendices.html#translation-services
   - https://packagecontrol.io/packages/DoxyDoxygen

Google is the default translator but youdao (or baidu) are also supported.

Hope it help
