### ISSUE TITLE
Package Control里面安装Chinese​Translator无效

### ISSUE THREAD

**Issue by kumiao** [toaol/sublime-translate#2]
我用的st3最新版，我在Package Control里面安装Chinese​Translator发现无法使用，我想问一下是不是只能在github上gitclone到package文件夹才能使用？

**Comment by toaol** [comment]
这个可能是由于快捷键发生了冲突，你可以试试 `Ctrl+Shift+P`，试试能不能找到 `Translate`，如果可以，那可能是快捷键冲突，你可以 clone 到 Packages 文件夹再更改一个快捷键。

**Comment by kumiao** [comment]
嗯，快捷键冲突，能找到translate，谢谢！

**Comment by zhilidali** [comment]
@toaol 更改快捷键的 command名称是什么？另外快捷键改成ctrl+shift+p不太好吧，最好换个，不然覆盖了命令面板的快捷键

**Comment by toaol** [comment]
额，我的意思是用 `C t r l +Shift + P` 打开控制面板看看能不能运行 translate 命令。

**Comment by toaol** [comment]
@zhilidali 额，我的意思是使用 `Ctrl + Shift + P` 打开命令面板看看能不能运行 translate 命令。
